-- ============================================================================
-- Migration: 00012_social_image_url
-- Description: Add image_url column to social_posts so posts can store a link
--              to either an uploaded image (Storage) or an AI-generated image.
--              Previous schema had only image_id → generated_images, which
--              didn't cover the user-upload case cleanly.
-- ============================================================================

ALTER TABLE public.social_posts
    ADD COLUMN IF NOT EXISTS image_url TEXT;

COMMENT ON COLUMN public.social_posts.image_url IS
    'Public URL of the image attached to the post — either uploaded to Supabase Storage or generated by AI. Null for text-only posts.';
