export const PLANS = {
  free: {
    name: "Free",
    priceMonthly: 0,
    priceYearly: 0,
    maxListings: 5,
    maxImages: 5,
    maxPhotoshoots: 0,
    maxSocial: 5,
    maxAds: 5,
    maxResearch: 0,
    features: [
      "5 product listings/month",
      "5 AI images (lifetime)",
      "5 social media posts/month",
      "5 ad copies/month",
    ],
  },
  starter: {
    name: "Starter",
    priceMonthly: 29,
    priceYearly: 278,
    maxListings: 50,
    maxImages: 100,
    maxPhotoshoots: 10,
    maxSocial: 50,
    maxAds: 50,
    maxResearch: 20,
    features: [
      "50 product listings/month",
      "100 AI images/month",
      "10 AI photoshoots/month",
      "50 social media posts/month",
      "50 ad creatives/month",
      "20 market research reports/month",
      "200+ ad creative templates",
      "Priority support",
    ],
  },
  pro: {
    name: "Pro",
    priceMonthly: 79,
    priceYearly: 758,
    maxListings: 300,
    maxImages: 300,
    maxPhotoshoots: 30,
    maxSocial: 300,
    maxAds: 300,
    maxResearch: 100,
    features: [
      "300 product listings/month",
      "300 AI images/month",
      "30 AI photoshoots/month",
      "300 social media posts/month",
      "300 ad creatives/month",
      "100 market research reports/month",
      "200+ ad creative templates",
      "Export to CSV/JSON",
      "Priority support",
    ],
    popular: true,
  },
  business: {
    name: "Business",
    priceMonthly: 149,
    priceYearly: 1430,
    maxListings: -1,
    maxImages: 1000,
    maxPhotoshoots: 100,
    maxSocial: -1,
    maxAds: -1,
    maxResearch: -1,
    features: [
      "Unlimited product listings",
      "1,000 AI images/month",
      "100 AI photoshoots/month",
      "Unlimited social media posts",
      "Unlimited ad creatives",
      "Unlimited market research",
      "200+ ad creative templates",
      "Export to CSV/JSON",
      "API access",
      "Dedicated support",
    ],
  },
} as const;

export const PLATFORMS = {
  amazon: { name: "Amazon", color: "#FF9900" },
  etsy: { name: "Etsy", color: "#F1641E" },
  shopify: { name: "Shopify", color: "#96BF48" },
  ebay: { name: "eBay", color: "#E53238" },
} as const;

export const SOCIAL_PLATFORMS = {
  instagram: { name: "Instagram", color: "#E1306C" },
  facebook: { name: "Facebook", color: "#1877F2" },
  pinterest: { name: "Pinterest", color: "#E60023" },
} as const;

export const AD_PLATFORMS = {
  facebook: { name: "Facebook/Instagram Ads", color: "#1877F2" },
  google: { name: "Google Ads", color: "#4285F4" },
} as const;
